version: '3.8'

networks:
  monitoring:
    driver: bridge
services:  

  influxdb:
    image: influxdb:latest
    ports:
     - "8083:8083"
     - "8086:8086"
     - "8090:8090"
     - "2003:2003"
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
      - INFLUXDB_DATA_ENGINE=tsm1
      - INFLUXDB_REPORTING_DISABLED=false
      - INFLUXDB_GRAPHITE_0_ENABLED=true
      - INFLUXDB_GRAPHITE_0_DATABASE=graphitedb
      - INFLUXDB_GRAPHITE_0_BIND_ADDRESS=:2003
      - INFLUXDB_GRAPHITE_PROTOCOL=tcp
      - INFLUXDB_GRAPHITE_BATCH_SIZE=1000

  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_INSTALL_PLUGINS=grafana-worldmap-panel,savantly-heatmap-panel,grafana-piechart-panel,grafana-clock-panel 

volumes:
  influxdb-storage:
  grafana-storage: